---
title: "Ch 1. Final figures"
author: "LiaC"
date: '2018-05-18'
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    code_folding: "show"
    self_contained: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Clear your environment first!
rm(list=ls())
knitr::opts_chunk$set(root.dir="/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/code", fig.path = "/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/") 
```

## Final figures for Chapter 1


### Top ten most abundant species by habitat type  
```{r dataprep, message=FALSE, warning=FALSE, tidy=TRUE, collapse=TRUE}
#load data
top16<- read.csv("/Users/Lia/Documents/Git/Fraser-salmon/all.data/2016catchsum.csv")

top16<- top16[,c(1:4)]
###Subset by habitat and pull out top ten species   
Mtop10_2016<- top16[which(top16$Habitat == c("Marsh")),]
Mtop10_2016<- subset(Mtop10_2016, Species %in% c("Three-spined stickleback", "Shiner surfperch", "Chinook", "Peamouth chub", "Chum", "Northern anchovy", "Staghorn sculpin", "Starry flounder", "Unidentified flatfish", "Pink"))
Mtop10_2016$Species<- factor(Mtop10_2016$Species) ## Drop unused levels
M16<- Mtop10_2016[order(Mtop10_2016$abundance, decreasing=TRUE),]
M16$Species<- factor(M16$Species, levels = c("Three-spined stickleback", "Chinook", "Peamouth chub", "Starry flounder", "Chum", "Shiner surfperch","Northern anchovy", "Staghorn sculpin","Unidentified flatfish", "Pink"))
  
  
EGtop10_2016<- top16[which(top16$Habitat == c("Eelgrass")),]
EGtop10_2016<- subset(EGtop10_2016, Species %in% c("Shiner surfperch", "Three-spined stickleback", "Bay pipefish", "Herring", "Surf smelt", "Pacific sand lance", "Tubesnout", "Starry flounder", "Saddleback gunnel", "Pile perch"))
EGtop10_2016$Species<- factor(EGtop10_2016$Species) ## Drop unused levels
EG16<- EGtop10_2016[order(EGtop10_2016$abundance, decreasing=TRUE),]
EG16$Species<- factor(EG16$Species, levels = c("Shiner surfperch", "Three-spined stickleback", "Bay pipefish", "Herring", "Surf smelt", "Pacific sand lance", "Tubesnout", "Starry flounder", "Saddleback gunnel", "Pile perch"))
##Shiners = 18,509, Stickleback = 6868   
##Manually reduce outlier numbers to fit on plot:  
EG16$abundance[which(EG16$Species%in%("Shiner surfperch"))]<-1000
EG16$abundance[which(EG16$Species%in%("Three-spined stickleback"))]<-1000
    
SFtop10_2016<- top16[which(top16$Habitat == c("Sand flat")),]
SFtop10_2016<- subset(SFtop10_2016, Species %in% c("Shiner surfperch", "Three-spined stickleback", "Northern anchovy", "Herring", "Unidentified flatfish", "Arrow goby", "Chinook", "Starry flounder", "Unidentified larval fish 2", "Sand sole"))
SFtop10_2016$Species<- factor(SFtop10_2016$Species) ## Drop unused levels
SF16<- SFtop10_2016[order(SFtop10_2016$abundance, decreasing=TRUE),]
SF16$Species<- factor(SF16$Species, levels = c("Shiner surfperch", "Northern anchovy", "Starry flounder", "Unidentified larval fish 2", "Three-spined stickleback", "Arrow goby", "Unidentified flatfish", "Chinook", "Herring", "Sand sole"))  
levels(SF16$Species)<- c("Shiner surfperch", "Northern anchovy", "Starry flounder", "Larval fish", "Three-spined stickleback", "Arrow goby", "Unidentified flatfish", "Chinook", "Herring", "Sand sole")
##Shiners = 2,373   
##Manually reduce outlier numbers to fit on plot:  
SF16$abundance[which(SF16$Species%in%("Shiner surfperch"))]<-1000
  
top17<- read.csv("/Users/Lia/Documents/Git/Fraser-salmon/all.data/2017catchsum.csv")
Mtop10_2017<- top17[which(top17$Habitat == c("Marsh")),]
Mtop10_2017<- subset(Mtop10_2017, Species %in% c("Three-spined stickleback", "Shiner surfperch", "Chinook", "Peamouth chub", "Chum", "Prickly sculpin", "Staghorn sculpin", "Starry flounder", "Unidentified flatfish", "Unidentified sculpin"))
Mtop10_2017$Species<- factor(Mtop10_2017$Species) ## Drop unused levels
M17<- Mtop10_2017[order(Mtop10_2017$abundance, decreasing=TRUE),]
M17$Species<- factor(M17$Species, levels = c("Unidentified flatfish", "Three-spined stickleback", "Starry flounder", "Chinook", "Staghorn sculpin", "Chum", "Peamouth chub", "Prickly sculpin", "Shiner surfperch", "Unidentified sculpin"))
  
EGtop10_2017<- top17[which(top17$Habitat == c("Eelgrass")),]
EGtop10_2017<- subset(EGtop10_2017, Species %in% c("Shiner surfperch", "Three-spined stickleback", "Bay pipefish", "Herring", "Surf smelt", "Pacific sand lance", "Tubesnout", "Starry flounder", "Chum", "Chinook"))
EGtop10_2017$Species<- factor(EGtop10_2017$Species) ## Drop unused levels
EG17<- EGtop10_2017[order(EGtop10_2017$abundance, decreasing=TRUE),]
EG17$Species<- factor(EG17$Species, levels = c("Three-spined stickleback", "Shiner surfperch", "Starry flounder", "Chum", "Herring", "Pacific sand lance", "Tubesnout",  "Chinook", "Surf smelt", "Bay pipefish"))
##Shiners = 3,734, Stickleback = 3,957    
##Manually reduce outlier numbers to fit on plot:  
EG17$abundance[which(EG17$Species%in%("Shiner surfperch"))]<-1000
EG17$abundance[which(EG17$Species%in%("Three-spined stickleback"))]<-1000
    
SFtop10_2017<- top17[which(top17$Habitat == c("Sand flat")),]
SFtop10_2017<- subset(SFtop10_2017, Species %in% c("Shiner surfperch", "Three-spined stickleback", "Chum", "Herring", "Unidentified flatfish", "Arrow goby", "Chinook", "Starry flounder", "Unidentified larval fish 2", "Pacific sand lance"))
SFtop10_2017$Species<- factor(SFtop10_2017$Species) ## Drop unused levels
SF17<- SFtop10_2017[order(SFtop10_2017$abundance, decreasing=TRUE),]
SF17$Species<- factor(SF17$Species, levels = c("Starry flounder", "Pacific sand lance","Shiner surfperch", "Unidentified flatfish", "Three-spined stickleback", "Chum", "Arrow goby", "Chinook", "Unidentified larval fish 2", "Herring"))
  

##Use whole data set for labels and legends  
top<- rbind(Mtop10_2016, Mtop10_2017, EGtop10_2016, EGtop10_2017, SFtop10_2016, SFtop10_2017)
levels(top$Species)
row.names(top)<- 1:59
##Add class back in (not in this data set - ugh)  
top$Class<- c(
"Migratory", "Migratory","Migratory","Migratory","Resident","Resident","Resident","Resident","Resident","Resident","Migratory","Migratory","Resident","Resident","Resident","Resident","Resident","Resident","Resident","Resident","Resident","Resident","Migratory","Resident","Resident","Resident","Resident","Migratory","Resident","Resident","Resident","Migratory","Migratory","Resident","Migratory","Resident","Resident","Migratory","Resident","Resident","Resident","Migratory","Resident","Migratory","Resident","Resident","Resident","Resident","Resident","Unclassified","Resident","Migratory","Migratory","Resident","Migratory","Resident","Resident","Resident","Resident"
)
  
###first tried facets -- doesn't work well because differing species orders, differing x axes.    
#p<- ggplot(top, aes(x = Species, y = abundance)) +   
 # geom_bar(stat = "identity", aes(fill = Species)) +  
  #for adding text on top of things
  #geom_text() +
  #facet_grid(Habitat~Year, scales = "free_x") +
  #colScale +
  #xScale +
  #theme_cowplot() +
  #labs(y = "", x = "") +
  #ylim(0, 1400) +
  #theme(
  #  legend.position = "left", 
  #  #plot.margin = unit(c(0,0,-0.6,0), "cm"),
  #  axis.title.y = element_text(margin=margin(0,20,0,0), size=14, face="bold"), 
  #  plot.title = element_text(size=14, margin=margin(20,0,40,0)),
  #  axis.text.x = element_text(angle = 45, size = 10, vjust = 1, hjust = 1)
  #)
 #print(p)

  
library(ggplot2)
library(cowplot)
library(gridExtra)
library(ggpubr)
## Create custom colour scale to match to species levels:  
sp_col<- c("firebrick","red","orangered","tomato1", "sienna1", "lightcoral",   "midnightblue","steelblue","darkslateblue", "royalblue1","royalblue4","dodgerblue","mediumblue","lightslateblue","deepskyblue","darkturquoise","lightseagreen","cyan","skyblue1","lightblue","paleturquoise", "gray87")
names(sp_col)<- c("Chinook","Chum","Pacific sand lance","Surf smelt", "Northern anchovy","Pink","Shiner surfperch","Three-spined stickleback","Starry flounder","Unidentified flatfish","Herring","Bay pipefish","Peamouth chub","Tubesnout","Staghorn sculpin","Prickly sculpin","Arrow goby","Sand sole","Pile perch","Saddleback gunnel","Unidentified sculpin","Larval fish")
colScale<- scale_fill_manual(values = sp_col, name = "Species") 

### V2 - more colour-blind and gray scale friendly
#library(viridis)
#sp_col<- c(viridis_pal(begin = 0, end = 1, direction = -1, option = "inferno")(21), "gray87")
#names(sp_col)<- c("Chinook","Chum","Pacific sand lance","Surf smelt", "Northern anchovy","Pink","Shiner surfperch","Three-spined stickleback","Starry flounder","Unidentified flatfish","Herring","Bay pipefish","Peamouth chub","Tubesnout","Staghorn sculpin","Prickly sculpin","Arrow goby","Sand sole","Pile perch","Saddleback gunnel","Unidentified sculpin","Larval fish")
#colScale<- scale_fill_manual(values = sp_col, name = "Species") 

legndorder<- as.data.frame(sp_col) 
rownames(legndorder)[1]<- c("Chinook salmon");rownames(legndorder)[2]<- c("Chum salmon"); rownames(legndorder)[6]<- c("Pink salmon"); rownames(legndorder)[11]<- c("Pacific Herring")
legndorder$order<- c(1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3)
mig_leg<- subset(legndorder, order ==1)
colScale_mig<- scale_fill_manual(values = mig_leg$sp_col, name = "Migratory")

res_leg<- subset(legndorder, order ==2)
colScale_res<- scale_fill_manual(values = res_leg$sp_col, name = "Resident")

un_leg<- subset(legndorder, order ==3)
colScale_un<- scale_fill_manual(values=un_leg$sp_col, name = "Unclassified")
  
##Try to create gradient scale for class... didn't get this working  
#class_col<- c("red", "red", "gray87", "royalblue1", "royalblue1")
#top2<- expand.grid(top$abundance,z=seq(-2,2, by=1))
#names(class_col)<- c("Migratory","Migratory","Unclassified", "Resident", "Resident")
#classScale<- scale_colour_manual(values = class_col, name = "Class")

  ##OLD:
#sp_labels<- c("Chinook"="Chinook","Chum"="Chum","Northern anchovy"="Northern \nanchovy","Peamouth chub"="Peamouth \nchub","Pink"="Pink","Shiner surfperch"="Shiner \nsurfperch","Staghorn sculpin"="Staghorn \nsculpin","Starry flounder"="Starry \nflounder","Three-spined stickleback"="Three-spined \nstickleback","Unidentified flatfish"="Unidentified \nflatfish","Prickly sculpin"="Prickly \nsculpin","Unidentified sculpin"="Unidentified \nsculpin","Bay pipefish"="Bay \npipefish","Herring"="Herring","Pacific sand lance"="Pacific \nsand lance","Pile perch"="Pile perch","Saddleback gunnel"="Saddleback \ngunnel","Surf smelt"="Surf smelt","Tubesnout"="Tubesnout","Arrow goby"="Arrow goby","Sand sole"="Sand sole","Unidentified larval fish 2"="Unidentified \nlarval fish 2")

##Create label scale common for all species that matches to colour scale 
sp_labels<- c("Chinook salmon"="Chinook","Chum salmon"="Chum","Northern anchovy"="Anch","Peamouth chub"="Peam","Pink salmon"="Pink","Shiner surfperch"="Shiner","Staghorn sculpin"="Stag","Starry flounder"="Starry","Three-spined stickleback"="TS stick","Unidentified flatfish"="Un Flat","Prickly sculpin"="Prickly","Unidentified sculpin"="Un Sculp","Bay pipefish"="Pipe","Pacific Herring"="Herring","Pacific sand lance"="SLance","Pile perch"="Pile","Saddleback gunnel"="Saddle","Surf smelt"="S smelt","Tubesnout"="Tubesnout","Arrow goby"="A goby","Sand sole"="Sole","Larval fish"="Larval")

xScale<- scale_x_discrete(labels = sp_labels)  
```
  
###MAIN PLOTS TO ARRANGE TOGETHER FOR FINAL PLOT: 1 for each habitat*year combo:  
```{r TopTenPanels,  tidy = TRUE, message=FALSE, warning=FALSE, fig.height=3, fig.width=3}  
#M16
mplot<- ggplot(M16, aes(x = Species, y = abundance)) + 
  geom_bar(stat = "identity", aes(fill = Species)) +
  colScale +
  xScale +
  theme_cowplot() +
  labs(y = "", x = "") +
  scale_y_continuous(breaks = c(0, 250, 500, 750, 1000, 1250, 1500), labels = c("0", "250", "500", "750", "1000", "1250", ""), expand=c(0,0)) + expand_limits(y=c(0,1400)) +
  theme(
    legend.position = "none", 
    #plot.margin = unit(c(1,0,-1,0), "cm"),
    #axis.title.y = element_text(margin=margin(0,20,0,0), size=14, face="bold"), 
    #plot.title = element_text(size=14, margin=margin(20,0,40,0)),
    axis.text.x = element_text(angle = 45, size = 10, vjust = 1, hjust = 1)
  )

#EG16
##Shiners = 18,509, Stickleback = 6868 
egplot<- ggplot(EG16, aes(x = Species, y = abundance)) + 
  geom_bar(stat = "identity", aes(fill = Species)) +
  colScale +
  xScale +
  theme_cowplot() +
  scale_y_continuous(breaks = c(0, 250, 500, 750, 1000), labels = c("0", "250", "500", "750", "1000"), expand = c(0,0)) + 
  expand_limits(y=c(0, 1050)) +
  labs(y = "", x = "") +
  theme(
    legend.position = "none", 
    #plot.margin = unit(c(1,0,-1,0), "cm"),
    #axis.title.y = element_text(margin=margin(0,10,0,0), size=14, face="bold"), 
    #plot.title = element_text(size=14, margin=margin(20,0,40,0)),
    axis.text.x = element_text(angle = 45, size = 10, vjust = 1, hjust = 1)
  )


#SF16
##Shiners = 2,373
splot<- ggplot(SF16, aes(x = Species, y = abundance)) + 
  geom_bar(stat = "identity", aes(fill = Species)) +
  colScale +
  xScale +
  theme_cowplot() +
  scale_y_continuous(breaks = c(0, 250, 500, 750, 1000), labels = c("0", "250", "500", "750", "1000"), expand = c(0,0)) + 
  expand_limits(y=c(0, 1050)) +
  labs(y = "", x = "") +
  theme(
    legend.position = "none", 
    #plot.margin = unit(c(0.5,0,-0.5,0), "cm"),
    #axis.title.y = element_text(margin=margin(0,20,0,0), size=14, face="bold"), 
    #plot.title = element_text(size=14, margin=margin(20,0,40,0)),
    axis.text.x = element_text(angle = 45, size = 10, vjust = 1, hjust = 1)
  )

#M17
mplot2<- ggplot(M17, aes(x = Species, y = abundance)) + 
  geom_bar(stat = "identity", aes(fill = Species)) +
  colScale +
  xScale +
  theme_cowplot() +
  labs(y = "", x = "") +
  scale_y_continuous(breaks = c(0, 250, 500, 750, 1000, 1250, 1500), labels = c("","","","","","",""), expand=c(0,0)) + expand_limits(y=c(0,1400)) +
  theme(
    #plot.margin = unit(c(1,1,-1,-1), "cm"),
    legend.position = "none", 
    #axis.title.y = element_text(margin=margin(0,20,0,0), size=14, face="bold"), 
    #plot.title = element_text(size=14, margin=margin(20,0,40,0)),
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 10)
  )

#EG17  
##Shiners = 3,734, Stickleback = 3,957
egplot2<- ggplot(EG17, aes(x = Species, y = abundance)) + 
  geom_bar(stat = "identity", aes(fill = Species)) +
  colScale +
  xScale +
  theme_cowplot() +
  labs(y = "", x = "") +
  scale_y_continuous(breaks = c(0, 250, 500, 750, 1000), labels = c("","","","",""), expand = c(0,0)) + 
  expand_limits(y=c(0, 1050)) +
  theme(
    #plot.margin = unit(c(1,1,-1,-1), "cm"),
    legend.position = "none", 
    #axis.title.y = element_text(margin=margin(0,20,0,0), size=14, face="bold"), 
    #plot.title = element_text(size=14, margin=margin(20,0,40,0)),
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 10)
  )

#SF17
splot2<- ggplot(SF17, aes(x = Species, y = abundance)) + 
  geom_bar(stat = "identity", aes(fill = Species)) +
  colScale +
  xScale +
  theme_cowplot() +
  scale_y_continuous(breaks = c(0, 250, 500, 750, 1000), labels =  c("","","","",""), expand = c(0,0)) + 
  expand_limits(y=c(0, 1050)) +
  labs(y = "", x = "") +
  theme(
    #plot.margin = unit(c(0.5,1,-0.5,-1), "cm"),
    legend.position = "none", 
    #axis.title.y = element_text(margin=margin(0,20,0,0), size=14, face="bold"), 
    #plot.title = element_text(size=14, margin=margin(20,0,40,0)),
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 10)
  )  
  
  
##### create plots for legends  (didn't end up using)
#p<- ggplot(top[which(top$Class == "Resident"),], aes(x = Species, y = abundance)) +
#  geom_bar(stat = "identity", aes(fill = Species))+
#  scale_fill_manual(values = sp_col, name = "Resident species") +
#  xScale +
#  theme_cowplot() +
#  labs(y = "", x = "", legend = "") +
#  theme(
#    legend.position = "right"
#  )
#print(p)
#p2<- ggplot(top[which(top$Class == "Migratory"),], aes(x = Species, y = abundance)) +
#  geom_bar(stat = "identity", aes(fill = Species))+
#  scale_fill_manual(values = sp_col, name = "Migratory species") +
#  xScale +
#  theme_cowplot() +
#  labs(y = "", x = "") +
#  theme(
#    legend.position = "right"
#  )
#print(p2)
#p3<- ggplot(top[which(top$Class == "Unclassified"),], aes(x = Species, y = abundance)) +
#  geom_bar(stat = "identity", aes(fill = Species))+
#  scale_fill_manual(values = sp_col, name = "Unclassified") +
#  xScale +
#  theme_cowplot() +
#  labs(y = "", x = "") +
#  theme(
#    legend.position = "right"
#  )
#print(p3)
#p4<- ggplot(top, aes(x = Species, y = abundance)) +
#  geom_bar(stat = "identity", aes(fill = Species))+
#  scale_fill_manual(values = sp_col, name = "Species", guide = guide_legend(ncol = 1)) +
#  xScale +
#  theme_cowplot() +
#  labs(y = "", x = "") +
#  theme(
#    legend.position = "right",legend.text = element_text(size = 10), legend.margin = unit(0, "mm")
#  )
#print(p4)

#p5<- ggplot(top2, aes(x = z, y = Var1)) +
#  geom_point(aes(colours=z))+
#  scale_colour_gradientn(values=classScale, colours=class_col) +
#theme(
#    legend.position = "right",legend.text = element_text(size = 10), legend.margin = unit(0, "mm")
#  )
#print(p5)  #couldn't get gradient working  
    
##legends
library(grid)
#legendGrob(2, 0.1, labels = c("Chinook (Chin)","Chum (Chum)","Northern anchovy (Anch)","Peamouth chub (Peam)","Pink (Pink)","Shiner surfperch (Shiner)","Staghorn sculpin (Stag)","Starry flounder (Starry)","Three-spined stickleback (TS stick)","Unidentified flatfish (Un Flat)","Prickly sculpin (Prickly)","Unidentified sculpin (Un Sculp)","Bay pipefish (Pipe)","Herring (Herring)","Pacific sand lance (SLance)","Pile perch (Pile)","Saddleback gunnel (Saddle)","Surf smelt (S smelt)","Tubesnout (Tubesnout)","Arrow goby (A goby)","Sand sole (Sole)","Unidentified larval fish 2 (Un larval)"), pch = 15, fill = colScale)
#legendspace = rectGrob(2, 0.1, gp = gpar(fill = "white"))
#legendspace + ggtitle(label = "Species") + theme(legend.box = "vertical")
  
#Try #2: use function to pull legend out of ggplots  
#g_legend<-function(a.gplot){  
#    tmp <- ggplot_gtable(ggplot_build(a.gplot))  
#    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")  
#    legend <- tmp$grobs[[leg]]   
#    legend  
#}  

#now create legends for each plot, and for all plots  
#reslegend <- g_legend(p)  
#miglegend <- g_legend(p2)  
#unlegend <- g_legend(p3)  
#alllegend<- g_legend(p4)   
#classlegend<- g_legend(p5)  
  
### MAKE THE PLOT  
#ggarrange(mplot, mplot2, reslegend, egplot, egplot2, miglegend, splot, splot2, unlegend, ncol=3, nrow=3, align = "h", widths = c(1,1,0.5))
  
#V2
#ggarrange(mplot, mplot2, alllegend, egplot, egplot2, legendspace, splot, splot2, ncol=3, nrow=3, align = "h", widths = c(1,1,0.6))  
  
#V3.2
#ggarrange(mplot, mplot2, legendgrob1, egplot, egplot2, legendspace, splot, splot2, ncol=3, nrow=3, align = "h", widths = c(1,1,0.6))  
  
#V4
#ggarrange(mplot, mplot2, egplot, egplot2, splot, splot2, ncol=2, nrow=3, align = "h", common.legend = TRUE, legend = "right")
  
#V3
#lay<- rbind(c(1,2,3),
 #           c(4,5,8),
 #           c(6,7,8))
#sp_labels<- levels(top$Species)  
#legends1<- list(legend=list(labels = sp_labels, title = "Species", colours = sp_col, border = "white"), legend=list( labels = c("Resident", "", "", "Migratory", "", "", "Unclassified"), colours = c("navy blue", "royalblue1", "lightblue", "tomato", "red", "salmon", "gray87"), title = "Class", border = c("navy blue", "royalblue1", "deepskyblue", "firebrick", "red", "pink", "gray87")))  
#library("BoutrosLab.plotting.general")
#legendgrob1<- legend.grob(legends = legends1, title.just = "left", title.cex=1, label.cex=1, size = 2, border=NULL)  
#my_plots=list(mplot, mplot2, egplot, egplot2, splot, splot2)  
#my_grobs<- lapply(my_plots, ggplotGrob) #tried to do in two lines of code but doesn't work  
  

#grid.arrange(grobs=my_grobs)  
    
#V5 -- closest so far
#ggarrange(arrangeGrob(mplot, mplot2, egplot, egplot2, splot, splot2, ncol=2),legendgrob1, ncol=3, nrow=3, align = "h", heights = c(3, 3,.75), widths = c(3,3,0.75))
```  
  
```{r FinalPlot,  tidy = TRUE, message=FALSE, warning=FALSE, fig.height=7.5, fig.width=8.5}  
################################## V6: BEST:
##Uses original ggplots from above, with colour and label scales identified prior. Does not use legend plots.   
###First should remove 2nd printout page by converting individually to ggplotGrobs... :/  
mplot<- ggplotGrob(mplot)
mplot2<- ggplotGrob(mplot2) 
egplot<-ggplotGrob(egplot) 
egplot2<- ggplotGrob(egplot2) 
splot<- ggplotGrob(splot) 
splot2<- ggplotGrob(splot2)
### uses manual legend grobs and layout matrix:  
library(BoutrosLab.plotting.general)
library(grid)
library(ggplot2)

#create custom layout matrix  
lay<- rbind(c(8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8),
            c(8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,8,3,3,3,3,3,3),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,3,3,3,3,3,3),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,3,3,3,3,3,3),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,3,3,3,3,3,3),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,3,3,3,3,3,3),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,3,3,3,3,3,3),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,8,8,8,8,8,8),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,8,8,8,8,8,8),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,8,8,8,8,8,8),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,8,8,8,8,8,8),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,8,8,8,8,8,8),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,8,8,8,8,8,8),
            c(8,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,8,8,8,8,8,8))
#create blank rectangle for margins and spaces  
legendspace = rectGrob(2,1,gp = gpar(fill = "blue", col=NULL))
  
#Create common legend for all plots  
#old - with all spp together
legends1<- list(legend=list(labels = sp_labels, title = "Species", title.fontface = "bold", colours = sp_col, border = "white", position="topright"), legend=list( labels = c("Migratory", "", "","Resident", "", "", "Unclassified"), colours = c("firebrick", "red", "pink","navy blue", "royalblue1", "deepskyblue", "gray87"), title = "Class", title.fontface = "bold", border = c("firebrick", "red", "pink", "navy blue", "royalblue1", "deepskyblue", "gray87"), position="topright"))
#turn into legend grob for grid arrange:
legendgrob1<- legend.grob(legends = legends1, title.just = "left", title.cex=1.1, label.cex=1, size = 2, border=NULL)
   
#new with categories
legends2<- list(legend=list(labels = rownames(mig_leg), title = "Migratory", title.fontface = "bold", colours = as.character(mig_leg$sp_col), border = "white", position="topright"), legend=list(labels = rownames(res_leg), title = "Resident", title.fontface = "bold", colours = as.character(res_leg$sp_col), border = "white", position="topright"),legend=list(labels = rownames(un_leg), title = "Unclassified", title.fontface = "bold", colours = as.character(un_leg$sp_col), border = "white", position="topright"))
#turn into legend grob for grid arrange:
legendgrob1<- legend.grob(legends = legends2, title.just = "left", title.cex=1.1, label.cex=1, size = 2, border=NULL)
   

#####Text annotations to add onto plots  
#EG16  
##Shiners = 18,509, Stickleback = 6,868
ellips1<- grobTree(textGrob("~", x=0.158, y=0.628, gp=gpar(col="midnightblue", fontsize=15, fontface="bold")))
ellips2<- grobTree(textGrob("~", x=0.182, y=0.628, gp=gpar(col="steelblue", fontsize=15, fontface="bold")))
abun1<- grobTree(textGrob("18509", x=0.17, y=0.65, gp=gpar(col="black", fontsize=10), rot=45))
abun2<- grobTree(textGrob("6868", x=0.195, y=0.65, gp=gpar(col="black", fontsize=10), rot=45))
  
#SF16
##Shiners = 2,373, Shiner
ellips3<- grobTree(textGrob("~", x=0.158, y=0.295, gp=gpar(col="midnightblue", fontsize=15, fontface="bold")))
abun3<- grobTree(textGrob("2373", x=0.169, y=0.317, gp=gpar(col="black", fontsize=10), rot=45))
  
#EG17  
##Shiners = 3,734, Stickleback = 3,957
ellips4<- grobTree(textGrob("~", x=0.4635, y=0.628, gp=gpar(col="steelblue", fontsize=15, fontface="bold")))
abun4<- grobTree(textGrob("3957", x=0.475, y=0.65, gp=gpar(col="black", fontsize=10), rot=45))
ellips5<- grobTree(textGrob("~", x=0.487, y=0.628, gp=gpar(col="midnightblue", fontsize=15, fontface="bold")))
abun5<- grobTree(textGrob("3734", x=0.5, y=0.65, gp=gpar(col="black", fontsize=10), rot=45))
  
#YEAR
yr1<- grobTree(textGrob("2016", x=0.27, y=0.965, gp=gpar(col="black", fontsize=14, fontface="bold")))
yr2<- grobTree(textGrob("2017", x=0.57, y=0.965, gp=gpar(col="black", fontsize=14, fontface="bold")))
  
#Axes
#ax_y1<-grobTree(textGrob("Total Catch", x=0.078, y=0.84, gp=gpar(col="black", fontsize=12), rot=90))
ax_y2<-grobTree(textGrob("Total Catch", x=0.078, y=0.534, gp=gpar(col="black", fontsize=12), rot=90))
#ax_y3<-grobTree(textGrob("Total Catch", x=0.078, y=0.21, gp=gpar(col="black", fontsize=12), rot=90))
  
#Habitat
a<-grobTree(textGrob("A", x=0.045, y=0.92, gp=gpar(col="black", fontsize=13, fontface="bold")))
b<-grobTree(textGrob("B", x=0.045, y=0.62, gp=gpar(col="black", fontsize=13, fontface="bold")))
c<-grobTree(textGrob("C", x=0.045, y=0.29, gp=gpar(col="black", fontsize=13, fontface="bold")))
  
  
###PLOT
#ggarrange(arrangeGrob(mplot, mplot2, legendgrob1, egplot, egplot2, splot, splot2,legendspace, layout_matrix = lay),align = "hv") + annotation_custom(abun1) + annotation_custom(abun2) + annotation_custom(ellips1) + annotation_custom(ellips2) + annotation_custom(ellips3) + annotation_custom(abun3) + annotation_custom(ellips4) + annotation_custom(abun4) + annotation_custom(ellips5) + annotation_custom(abun5) + annotation_custom(yr1) + annotation_custom(yr2) + annotation_custom(ax_y1) + annotation_custom(ax_y2) + annotation_custom(ax_y3) + annotation_custom(a) + annotation_custom(b) + annotation_custom(c)

ggarrange(arrangeGrob(mplot, mplot2, legendgrob1, egplot, egplot2, splot, splot2,legendspace, layout_matrix = lay),align = "hv") + annotation_custom(abun1) + annotation_custom(abun2) + annotation_custom(ellips1) + annotation_custom(ellips2) + annotation_custom(ellips3) + annotation_custom(abun3) + annotation_custom(ellips4) + annotation_custom(abun4) + annotation_custom(ellips5) + annotation_custom(abun5) + annotation_custom(yr1) + annotation_custom(yr2) + annotation_custom(ax_y2) + annotation_custom(a) + annotation_custom(b) + annotation_custom(c)
 
#pdf
ggsave("/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/Fig3_TopTenAbund.pdf", height=7.5, width=8.5, colormodel = "cmyk")  #specify size to make sure doesn't get distorted  
#png
ggsave("/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/Fig3_TopTenAbund.png", height=7.5, width=8.5, dpi = 800)

#pdf old
#ggsave("/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/TopTenAbundgg.pdf", height=7.5, width=8.5)  #specify size to make sure doesn't get distorted  
#png old
#ggsave("/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/TopTenAbundgg.png", height=7.5, width=8.5, dpi = 800)
```
   
### Abiotic 1: Temperature by habitat + year  
```{r abiotic1, collapse=TRUE, dev='png', dpi=400, fig.width=8, fig.height=8}
############# compare both years of abiotic data
##Simple scatter plots
all<- read.csv("/Users/Lia/Documents/Git/Fraser-salmon/all.data/all_clean.csv")
  
##Summary stats to compare means between years for each month (round 2:8 were in common)  
summary(all$Temp.surf)
t.test(Temp.surf~as.factor(Year), data = all) #overall temp is sig diff 
#subset round 2:8
comp<- subset(all, round %in% c(2:8)) #note this does not include round 7.5, but was having trouble including it in t.test even when it was part of comp and it was just extra sampling effort in 2016 so decided to leave it out anyways. 
t.test(Temp.surf~as.factor(Year), data = comp) #still significant
sd(comp$Temp.surf[comp$Year == 0]) #2016 SD = 1.810312
sd(comp$Temp.surf[comp$Year ==1]) #2017 SD = 2.527523
var.test(Temp.surf~as.factor(Year), data = comp) #vars not equal so use Welch's (default) 

comp0<- subset(comp, Year == 0)
comp1<- subset(comp, Year == 1)
#note that because variable lengths differ, can't do t-tests on subsets. Can use to get means and sds though.
#2016
mean(comp0$Temp.surf[comp0$round==2])
sd(comp0$Temp.surf[comp0$round==2])
mean(comp0$Temp.surf[comp0$round==3:4])
sd(comp0$Temp.surf[comp0$round==3:4])
mean(comp0$Temp.surf[comp0$round==5:6])
sd(comp0$Temp.surf[comp0$round==5:6])
mean(comp0$Temp.surf[comp0$round==7])
sd(comp0$Temp.surf[comp0$round==7])
mean(comp0$Temp.surf[comp0$round==8])
sd(comp0$Temp.surf[comp0$round==8])
#2017
mean(comp1$Temp.surf[comp1$round==2])
sd(comp1$Temp.surf[comp1$round==2])
mean(comp1$Temp.surf[comp1$round%in%3:4])
sd(comp1$Temp.surf[comp1$round%in%3:4])
mean(comp1$Temp.surf[comp1$round%in%5:6])
sd(comp1$Temp.surf[comp1$round%in%5:6])
mean(comp1$Temp.surf[comp1$round==7])
sd(comp1$Temp.surf[comp1$round==7])
mean(comp1$Temp.surf[comp1$round==8])
sd(comp1$Temp.surf[comp1$round==8])


#Compare month by month
var.test(Temp.surf~as.factor(Year), subset = comp$round == 2, data=comp) ##Tested variance for each round sequentially and all significantly different (round 3 almost not at 0.03), therefore should use Welch's T-test for all (reduced df to deal with unequal var)    

t.test(Temp.surf~as.factor(Year), subset = comp$round == 2, data=comp) #March 

t.test(Temp.surf~as.factor(Year), subset = comp$round %in% 3:4, data=comp) #April   
t.test(Temp.surf~as.factor(Year), subset = comp$round %in% 5:6, data=comp) #May   
t.test(Temp.surf~as.factor(Year), subset = comp$round == 7, data=comp) #June  
t.test(Temp.surf~as.factor(Year), subset = comp$round == 8, data=comp) #July  

####Aggregate to look at means over time by habitat type
library(tidyverse)
  
temp<- all %>% group_by(Year, round, Habitat, month) %>% summarise(Temp = mean(Temp.surf), Temp.sd = sd(Temp.surf)) 
  
#subset data for lines
t16<- temp[c(temp$Year == 0),]
t17<- temp[c(temp$Year == 1),]  

#set colour pallette for years
COL <- adjustcolor(c("black", "white")[as.factor(temp$Year)], alpha.f = 0.8)
ylabs<- as.vector(seq(5, 20, by=5))
x0<-jitter(temp$round)
y0<-temp$Temp-temp$Temp.sd
y1<-temp$Temp+temp$Temp.sd

###########  Temp
plot(x=jitter(temp$round), y=temp$Temp, data = temp, type = 'n', xlim=c(0.5, 10), las=1, ylim=c(4, 20), ylab = "",
     main="", cex.axis = 1, lwd=1, bty = "l", xlab = " ", xaxt='n', yaxt='n') %/%
  lines(Temp~round, data=t16[c(t16$Habitat == "Marsh"),], col=alpha("black", 0.6), lty=4) %/% lines(Temp~round, data=t16[c(t16$Habitat == "Eelgrass"),], col=alpha("black", 0.6), lty=5) %/% lines(Temp~round, data=t16[c(t16$Habitat == "Sand flat"),], col=alpha("black", 0.6)) %/% lines(Temp~round, data=t17[c(t17$Habitat == "Marsh"),], col=alpha("gray", 0.6), lty=4) %/% lines(Temp~round, data=t17[c(t17$Habitat == "Eelgrass"),], col=alpha("gray", 0.6), lty=5) %/% lines(Temp~round, data=t17[c(t17$Habitat == "Sand flat"),], col=alpha("gray", 0.6)) %/%
  #arrows(x0, y0, x1=x0, y1, length=0.05, angle= 90, code=3, col=alpha(c("gray"),0.5)) %/%
  points(x=jitter(temp$round), y=temp$Temp, type='p',cex = 1.6,bg = COL, pch=c(21,24,22)[as.numeric(temp$Habitat)])%/%
axis(side = 1, at = c(1.5, 4, 6, 8, 10), labels= c("March", "April", "May", "July", "October"), tck =-0.02) %/%
mtext(expression(paste("     Temperature", ~degree, "C")), side = 2,cex = 1.3, line = 2 , outer= FALSE ) %/%
  axis(side = 2, at = seq(3.5,20.5, by=.5), labels= FALSE, tck =-0.01) %/%
  axis(side = 2, at = seq(4,20, by=1), labels= FALSE, tck =-0.03) %/%
  text(y = seq(5,20, by=5), labels = ylabs, par("usr")[1], pos = 2, cex = 1, xpd=TRUE); legend(0.2,21.3, pt.bg = c(COL[1:3]), c("Marsh","Eelgrass","Sandflat"), cex = 1, lwd = 1.5, pt.lwd=1, pt.cex=1.3, bty='n', pch=c(24,21,22), lty = c(4,5,1), col=alpha("black", 0.6));legend(0.27,17.8, c("2016", "2017"), pt.bg =c(COL[1], COL[33]), pch=22, cex = 1, pt.cex = 1.3, x.intersp = 2, bty='n')
  

dev.print(png("/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/Temperature.png"), width = 8, height = 8)
```
  
### Abiotic 2: Salinity by habitat + year  
```{r salinity, fig.path = '/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/', dev='png', dpi=400, tidy=TRUE, collapse=TRUE}

#test if significantly different between years  
t.test(Sal.surf~as.factor(Year), data = comp)
sd(comp$Sal.surf[comp$Year == 0]) 
sd(comp$Sal.surf[comp$Year ==1]) 
var.test(Sal.surf~as.factor(Year), data = comp) #vars not equal so use Welch's (default) 

#2016
mean(comp0$Sal.surf[comp0$round==2])
sd(comp0$Sal.surf[comp0$round==2])
mean(comp0$Sal.surf[comp0$round==3:4])
sd(comp0$Sal.surf[comp0$round==3:4])
mean(comp0$Sal.surf[comp0$round==5:6])
sd(comp0$Sal.surf[comp0$round==5:6])
mean(comp0$Sal.surf[comp0$round==7])
sd(comp0$Sal.surf[comp0$round==7])
mean(comp0$Sal.surf[comp0$round==8])
sd(comp0$Sal.surf[comp0$round==8])
#2017
mean(comp1$Sal.surf[comp1$round==2])
sd(comp1$Sal.surf[comp1$round==2])
mean(comp1$Sal.surf[comp1$round%in%3:4])
sd(comp1$Sal.surf[comp1$round%in%3:4])
mean(comp1$Sal.surf[comp1$round%in%5:6])
sd(comp1$Sal.surf[comp1$round%in%5:6])
mean(comp1$Sal.surf[comp1$round==7])
sd(comp1$Sal.surf[comp1$round==7])
mean(comp1$Sal.surf[comp1$round==8])
sd(comp1$Sal.surf[comp1$round==8])


#Compare month by month
var.test(Sal.surf~as.factor(Year), subset = comp$round == 8, data=comp) ##Tested variance for each round sequentially and both 2 and 5:6 are NOT sig different, but rest are. Used Welch's for consistency.

t.test(Sal.surf~as.factor(Year), subset = comp$round %in% 2, data=comp) #March 

t.test(Sal.surf~as.factor(Year), subset = comp$round %in% 3:4, data=comp) #April   
t.test(Sal.surf~as.factor(Year), subset = comp$round %in% 5:6, data=comp) #May   
t.test(Sal.surf~as.factor(Year), subset = comp$round == 7, data=comp) #June  
t.test(Sal.surf~as.factor(Year), subset = comp$round == 8, data=comp) #July



####Aggregate to look at means over time by habitat type
library(tidyverse)
  
data<- all %>% group_by(Year, Habitat) %>% summarise(DO = mean(DOmg.surf), DO.sd = sd(DOmg.surf), pH = mean(pH.surf), pH.sd = sd(pH.surf), Sal = mean(Sal.surf), Sal.sd = sd(Sal.surf), Temp = mean(Temp.surf), Temp.sd = sd(Temp.surf)) 
#add numeric X values for habitat  
data$hab<- as.numeric(c(1.7,1.4,2,1.8,1.5,2.1))

#set colour pallette for years
COL <- adjustcolor(c("black", "white")[as.factor(data$Year)], alpha.f = 0.8)
  
###########  Sal

#define y axis labels  
ylabs<- as.vector(seq(0, 30, by=5))

#define sd lines
sdup<- data$Sal+data$Sal.sd
sdlow<- data$Sal-data$Sal.sd

###########  Plot
attach(data)
plot(Sal~hab, data = data, type = 'n', las=1,  ylab = "",ylim=c(0, 31),yaxt='n', xlim=c(1.3,2.2),
     main="", cex = 1.6,cex.axis = 1, lwd=1, bty = "l", xaxt='n', xlab="")%/%
  arrows(hab, Sal-Sal.sd, hab, Sal+Sal.sd, length=0.05, angle= 90, code=3, col=alpha(c("black", "gray"),0.6)[as.factor(data$Year)]) %/%
  points(hab, Sal, type='p', bg = COL, pch=c(21,24,22)[as.numeric(data$Habitat)]) %/%
  axis(side = 1, at = c(1.45, 1.75, 2.05), labels= c("Marsh", "Eelgrass", "Sand flat"), tck =-0.02) %/%
mtext(expression(paste("     Salinity (ppt)")), side = 2,cex = 1.3, line = 2 , outer= FALSE ) %/%
  axis(side = 2, at = seq(0,32, by=1), labels= FALSE, tck =-0.01) %/%
  axis(side = 2, at = seq(0,32, by=5), labels= FALSE, tck =-0.03) %/%
  text(y = seq(0,30, by=5), labels = ylabs, par("usr")[1], pos = 2, cex = 1, xpd=TRUE); legend(1.3,33.5, c("2016", "2017"), pt.bg =c(COL[1], COL[33]), pch=22, cex = 1, pt.cex = 1.3, x.intersp = 2,bty='n')

dev.print(png(salinity))
```
  
### Abiotic 3: Dissolved Oxygen by habitat + year  
```{r abiotic3, message=FALSE, warning=FALSE, tidy=TRUE, collapse=TRUE}
###########  DO
  
#test if significantly different between years  
t.test(DOmg.surf~as.factor(Year), data = comp)
sd(comp$DOmg.surf[comp$Year == 0]) #2016 SD = 1.810312
sd(comp$DOmg.surf[comp$Year ==1]) #2017 SD = 2.527523
var.test(DOmg.surf~as.factor(Year), data = comp) #vars not equal so use Welch's (default) 

#2016
mean(comp0$DOmg.surf[comp0$round==2])
sd(comp0$DOmg.surf[comp0$round==2])
mean(comp0$DOmg.surf[comp0$round==3:4])
sd(comp0$DOmg.surf[comp0$round==3:4])
mean(comp0$DOmg.surf[comp0$round==5:6])
sd(comp0$DOmg.surf[comp0$round==5:6])
mean(comp0$DOmg.surf[comp0$round==7])
sd(comp0$DOmg.surf[comp0$round==7])
mean(comp0$DOmg.surf[comp0$round==8])
sd(comp0$DOmg.surf[comp0$round==8])
#2017
mean(comp1$DOmg.surf[comp1$round==2])
sd(comp1$DOmg.surf[comp1$round==2])
mean(comp1$DOmg.surf[comp1$round%in%3:4])
sd(comp1$DOmg.surf[comp1$round%in%3:4])
mean(comp1$DOmg.surf[comp1$round%in%5:6])
sd(comp1$DOmg.surf[comp1$round%in%5:6])
mean(comp1$DOmg.surf[comp1$round==7])
sd(comp1$DOmg.surf[comp1$round==7])
mean(comp1$DOmg.surf[comp1$round==8])
sd(comp1$DOmg.surf[comp1$round==8])


#Compare month by month
var.test(DOmg.surf~as.factor(Year), subset = comp$round == 2, data=comp) ##Tested variance for each round sequentially and all significantly different, therefore should use Welch's T-test for all (reduced df to deal with unequal var)    

t.test(DOmg.surf~as.factor(Year), subset = comp$round == 2, data=comp) #March 

t.test(DOmg.surf~as.factor(Year), subset = comp$round %in% 3:4, data=comp) #April   
t.test(DOmg.surf~as.factor(Year), subset = comp$round %in% 5:6, data=comp) #May   
t.test(DOmg.surf~as.factor(Year), subset = comp$round == 7, data=comp) #June  
t.test(DOmg.surf~as.factor(Year), subset = comp$round == 8, data=comp) #July

#define y axis labels  
ylabs<- as.vector(seq(8,14,by=2))

#define sd lines
sdup<- data$DO+data$DO.sd
sdlow<- data$DO-data$DO.sd

###########  Plot
attach(data)
plot(DO~hab, data = data, type = 'n', las=1,  ylab = "",ylim=c(7, 14),yaxt='n', xlim=c(1.3,2.2),
     main="", cex = 1.6,cex.axis = 1, lwd=1, bty = "l", xaxt='n', xlab="")%/%
  arrows(hab, DO-DO.sd, hab, DO+DO.sd, length=0.05, angle= 90, code=3, col=alpha(c("black", "gray"),0.6)[as.factor(data$Year)]) %/%
  points(hab, DO, type='p', bg = COL, pch=c(21,24,22)[as.numeric(data$Habitat)]) %/%
  axis(side = 1, at = c(1.45, 1.75, 2.05), labels= c("Marsh", "Eelgrass", "Sand flat"), tck =-0.02) %/%
mtext(expression(paste("     Dissolved Oxygen (mg/L)")), side = 2,cex = 1.3, line = 2 , outer= FALSE ) %/%
  axis(side = 2, at = seq(7,14, by=.5), labels= FALSE, tck =-0.01) %/%
  axis(side = 2, at = seq(7,14, by=1), labels= FALSE, tck =-0.03) %/%
  text(y = seq(8,14, by=2), labels = ylabs, par("usr")[1], pos = 2, cex = 1, xpd=TRUE); legend(1.3,14.5, c("2016", "2017"), pt.bg =c(COL[1], COL[33]), pch=22, cex = 1, pt.cex = 1.3, x.intersp = 2,bty='n')

dev.print(pdf,"/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/DissOx.pdf")
```
  
### Abiotic 4: pH by habitat + year  
```{r abiotic4, message=FALSE, warning=FALSE, tidy=TRUE, collapse=TRUE}

###########  pH
  
#test if significantly different between years  
t.test(pH.surf~as.factor(Year), data = comp)
sd(comp$pH.surf[comp$Year == 0]) 
sd(comp$pH.surf[comp$Year ==1]) 
var.test(pH.surf~as.factor(Year), data = comp) #vars not equal so use Welch's (default) 

#2016
mean(comp0$pH.surf[comp0$round==2])
sd(comp0$pH.surf[comp0$round==2])
mean(comp0$pH.surf[comp0$round==3:4])
sd(comp0$pH.surf[comp0$round==3:4])
mean(comp0$pH.surf[comp0$round==5:6])
sd(comp0$pH.surf[comp0$round==5:6])
mean(comp0$pH.surf[comp0$round==7])
sd(comp0$pH.surf[comp0$round==7])
mean(comp0$pH.surf[comp0$round==8])
sd(comp0$pH.surf[comp0$round==8])
#2017
mean(comp1$pH.surf[comp1$round==2])
sd(comp1$pH.surf[comp1$round==2])
mean(comp1$pH.surf[comp1$round%in%3:4])
sd(comp1$pH.surf[comp1$round%in%3:4])
mean(comp1$pH.surf[comp1$round%in%5:6])
sd(comp1$pH.surf[comp1$round%in%5:6])
mean(comp1$pH.surf[comp1$round==7])
sd(comp1$pH.surf[comp1$round==7])
mean(comp1$pH.surf[comp1$round==8])
sd(comp1$pH.surf[comp1$round==8])


#Compare month by month
var.test(pH.surf~as.factor(Year), subset = comp$round == 2, data=comp) ##Tested variance for each round sequentially and all are sig diff. Used Welch's.

t.test(pH.surf~as.factor(Year), subset = comp$round %in% 2, data=comp) #March 

t.test(pH.surf~as.factor(Year), subset = comp$round %in% 3:4, data=comp) #April   
t.test(pH.surf~as.factor(Year), subset = comp$round %in% 5:6, data=comp) #May   
t.test(pH.surf~as.factor(Year), subset = comp$round == 7, data=comp) #June  
t.test(pH.surf~as.factor(Year), subset = comp$round == 8, data=comp) #July


#define y axis labels  
ylabs<- as.vector(seq(7,8.5,by=0.5))

#define sd lines
sdup<- data$pH+data$pH.sd
sdlow<- data$pH-data$pH.sd

###########  Plot
attach(data)
plot(pH~hab, data = data, type = 'n', las=1,  ylab = "",ylim=c(7, 9),yaxt='n', xlim=c(1.3,2.2),
     main="", cex = 1.6,cex.axis = 1, lwd=1, bty = "l", xaxt='n', xlab="")%/%
  arrows(hab, pH-pH.sd, hab, pH+pH.sd, length=0.05, angle= 90, code=3, col=alpha(c("black", "gray"),0.6)[as.factor(data$Year)]) %/%
  points(hab, pH, type='p', bg = COL, pch=c(21,24,22)[as.numeric(data$Habitat)]) %/%
  axis(side = 1, at = c(1.45, 1.75, 2.05), labels= c("Marsh", "Eelgrass", "Sand flat"), tck =-0.02) %/%
mtext(expression(paste("     pH (logarithmic scale)")), side = 2,cex = 1.3, line = 2 , outer= FALSE ) %/%
  axis(side = 2, at = seq(7,9, by=.1), labels= FALSE, tck =-0.01) %/%
  axis(side = 2, at = seq(7,9, by=.50), labels= FALSE, tck =-0.03) %/%
  text(y = seq(7,8.5, by=.5), labels = ylabs, par("usr")[1], pos = 2, cex = 1, xpd=TRUE); legend(1.3,9.15, c("2016", "2017"), pt.bg =c(COL[1], COL[33]), pch=22, cex = 1, pt.cex = 1.3, x.intersp = 2,bty='n')

dev.print(pdf,"/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/pH.pdf")


```

  
##final tripanel abiotic
```{r panel abiotic final, tidy=TRUE, fig.height=8, fig.width=3,, dpi=300, dev='pdf'}
  
#plot  
  
####Aggregate to look at means over time by habitat type
library(tidyverse)
  
data<- all %>% group_by(Year, Habitat) %>% summarise(DO = mean(DOmg.surf), DO.sd = sd(DOmg.surf), pH = mean(pH.surf), pH.sd = sd(pH.surf), Sal = mean(Sal.surf), Sal.sd = sd(Sal.surf), Temp = mean(Temp.surf), Temp.sd = sd(Temp.surf)) 
#add numeric X values for habitat  
data$hab<- as.numeric(c(1.7,1.4,2,1.8,1.5,2.1))

#set colour pallette for years
COL <- adjustcolor(c("black", "white")[as.factor(data$Year)], alpha.f = 0.8)
shapes<-c(21,24,22)
#define y axis labels  
sal.ylabs<- as.vector(seq(0, 30, by=5))
do.ylabs<- as.vector(seq(8,14,by=2))
ph.ylabs<- as.vector(seq(7,8.5,by=0.5))
  #mar = c(2.5,3,1,0)
###########  Plot
attach(data)
par(mfrow = c(3,1), mar = c(0,3,1,0), oma = c(2.5,0.5,0,0.5)); plot(Sal~hab, data = data, type = 'n', las=1,  ylab = "",ylim=c(0, 31),yaxt='n', xlim=c(1.3,2.2),
     main="", cex = 3,cex.axis = 1, lwd=1, bty = "l", xaxt='n', xlab="")%/%
  arrows(hab, Sal-Sal.sd, hab, Sal+Sal.sd, length=0.05, angle= 90, code=3, col=alpha(c("black", "gray"),0.6)[as.factor(data$Year)]) %/%
  points(hab, Sal, type='p', bg = COL, pch=c(21,24,22)[as.numeric(data$Habitat)]) %/%
mtext(expression(paste("     Salinity (ppt)")), side = 2,cex = .8, line = 2 , outer= FALSE ) %/%
  text(2.2,31.5, expression(paste("a)")),cex = 1.1) %/%
  axis(side = 2, at = seq(0,32, by=1), labels= FALSE, tck =-0.01) %/%
  axis(side = 2, at = seq(0,32, by=5), labels= FALSE, tck =-0.03) %/%
  text(y = seq(0,30, by=5), labels = sal.ylabs, par("usr")[1], pos = 2, cex = 1, xpd=TRUE); legend(1.3,33.5, c("2016", "2017"), pt.bg =c(COL[1], COL[33]), pch=22, cex = 1.1, pt.cex = 1.3, x.intersp = 2,bty='n'); plot(DO~hab, data = data, type = 'n', las=1,  ylab = "",ylim=c(7, 14),yaxt='n', xlim=c(1.3,2.2),
     main="", cex = 3,cex.axis = 1, lwd=1, bty = "l", xaxt='n', xlab="")%/%
  arrows(hab, DO-DO.sd, hab, DO+DO.sd, length=0.05, angle= 90, code=3, col=alpha(c("black", "gray"),0.6)[as.factor(data$Year)]) %/%
  points(hab, DO, type='p', bg = COL, pch=c(21,24,22)[as.numeric(data$Habitat)]) %/%
mtext(expression(paste("     Dissolved Oxygen (mg/L)")), side = 2,cex = .8, line = 2 , outer= FALSE ) %/%
  text(2.2,14, expression(paste("b)")),cex = 1.1) %/%
  axis(side = 2, at = seq(7,14, by=.5), labels= FALSE, tck =-0.01) %/%
  axis(side = 2, at = seq(7,14, by=1), labels= FALSE, tck =-0.03) %/%
  text(y = seq(8,14, by=2), labels = do.ylabs, par("usr")[1], pos = 2, cex = 1, xpd=TRUE);plot(pH~hab, data = data, type = 'n', las=1,  ylab = "",ylim=c(7, 9),yaxt='n', xlim=c(1.3,2.2),
     main="", cex = 3,cex.axis = 1, lwd=1, bty = "l", xaxt='n', xlab="")%/%
  arrows(hab, pH-pH.sd, hab, pH+pH.sd, length=0.05, angle= 90, code=3, col=alpha(c("black", "gray"),0.6)[as.factor(data$Year)]) %/%
  points(hab, pH, type='p', bg = COL, pch=c(21,24,22)[as.numeric(data$Habitat)]) %/%
  axis(side = 1, at = c(1.45, 1.75, 2.05), labels= c("Marsh", "Eelgrass", "Sand flat"), tck =-0.02) %/%
mtext(expression(paste("     pH (logarithmic scale)")), side = 2,cex = 0.8, line = 2 , outer= FALSE ) %/%
  text(2.2,9, expression(paste("c)")),cex = 1.1) %/%
  axis(side = 2, at = seq(7,9, by=.1), labels= FALSE, tck =-0.01) %/%
  axis(side = 2, at = seq(7,9, by=.50), labels= FALSE, tck =-0.03) %/%
  text(y = seq(7,8.5, by=.5), labels = ph.ylabs, par("usr")[1], pos = 2, cex = 1, xpd=TRUE)  

dev.print(pdf,"/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/panel_abiotic.pdf", width = 3, height = 8)

```
  
## Model output panel plot
```{r abundance model ggplot,  tidy = TRUE, message=FALSE, warning=FALSE, fig.height=5, fig.width=12}
  
##Note code for original plots is in purse.models.new.Rmd and marsh.models.new.Rmd --> load data and run parameter plot for each first.  

#plot  
  
library(gridExtra) #need for arrangeGrob
library(ggpubr) #need for ggarrange
library(BoutrosLab.plotting.general) #need for custom legend grob  

##Note need to use arrangeGrob to ensure saves correctly with all 8 plots in one.  
  
#Create legends for all plots?  
#marsh_legend<- list(legend=list( labels = c("Early Spring", "Summer", "Fall"), colours = c("lightskyblue","mediumblue","midnightblue"), title = "Marsh", border = "white", position="topright"))
#turn into legend grob for grid arrange:
#marsh_legend<- legend.grob(legends = marsh_legend, title.just = "left", title.cex=1.3, label.cex=1, size=2, border=NULL)
  
#Convert plots to grobs  
gg.purse.chin<- ggplotGrob(gg.purse.chin)
gg.purse.chum<- ggplotGrob(gg.purse.chum)
gg.purse.migra<- ggplotGrob(gg.purse.migra)
gg.purse.res<- ggplotGrob(gg.purse.res)
gg.beach.chin<- ggplotGrob(gg.beach.chin)
gg.beach.chum<- ggplotGrob(gg.beach.chum)
gg.beach.migra<- ggplotGrob(gg.beach.migra)
gg.beach.res<- ggplotGrob(gg.beach.res)  

## Add panel labels
a<- grobTree(textGrob("a", x=0.107, y=0.92, gp=gpar(col="black", fontsize=13, fontface="bold")))
b<- grobTree(textGrob("b", x=0.36, y=0.92, gp=gpar(col="black", fontsize=13, fontface="bold")))
c<-grobTree(textGrob("c", x=0.608, y=0.92, gp=gpar(col="black", fontsize=13, fontface="bold")))
d<-grobTree(textGrob("d", x=0.862, y=0.92, gp=gpar(col="black", fontsize=13, fontface="bold")))
e<-grobTree(textGrob("e", x=0.103, y=0.47, gp=gpar(col="black", fontsize=13, fontface="bold")))
f<-grobTree(textGrob("f", x=0.36, y=0.47, gp=gpar(col="black", fontsize=13, fontface="bold")))
g<-grobTree(textGrob("g", x=0.61, y=0.47, gp=gpar(col="black", fontsize=13, fontface="bold")))
h<-grobTree(textGrob("h", x=0.8523, y=0.47, gp=gpar(col="black", fontsize=13, fontface="bold")))

#plot together
ggarrange(arrangeGrob(gg.beach.chin, gg.beach.chum, gg.beach.migra, gg.beach.res, gg.purse.chin, gg.purse.chum, gg.purse.migra, gg.purse.res, nrow=2, ncol=4), heights = c(1+3/4,1), align = "v")+ annotation_custom(a) + annotation_custom(b) + annotation_custom(c)+ annotation_custom(d) + annotation_custom(e) + annotation_custom(f)+ annotation_custom(g) + annotation_custom(h)

 

ggsave("/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/Fig6_Model_parameter_panel.pdf", width=10, height=5) ##specify size to match fig.height and fig.width that I set in knit, to fit all on one.
ggsave("/Users/Lia/Documents/Git/Fraser-salmon/Ch1.Seasonal_diversity/final.figures/Fig6_Model_parameter_panel.png", width=10, height=5) 

```
